apiVersion: v1
kind: Secret
metadata:
  name: bitwarden-cli
stringData:
  BW_CLIENTID: ENC[AES256_GCM,data:XIoFdgBYbI07Xwohey44qpEYsehLn3gXJCiO5Y1thcfrzJvzSCdajMI=,iv:jMzLSpX3nY05asYt/yKPtzQkZ3RJadG7h/q69EB5gWE=,tag:BEqtNYoeBE8SjyatR9NObw==,type:str]
  BW_CLIENTSECRET: ENC[AES256_GCM,data:PmH+GaPmnicwXrqQHBDrUqlClndEbBWdsq3yVNQL,iv:+JOcRYhehQ9O1mbU6+/s85qEr3QtXgFwltLKwvGHvf4=,tag:knHvtaFjpwJj9bNT8/cgxQ==,type:str]
  BW_PASSWORD: ENC[AES256_GCM,data:WVfN4DtKZSB71MZMR/3uKL/CSjBoV3Db/bA=,iv:yMOi6t49Q6cMqs1mSHvAkAZ/6+UuGU8lKlzSG6PPcEk=,tag:xDFMMVIlMWRz73R8AH8jdA==,type:str]
  BW_USER: ENC[AES256_GCM,data:63wXsIeh9AUJEGkcRqml1IYDP375JLs=,iv:1di26kvAlLyd8YMusIVZDTMxJW88yh58HutNl+Mq1i8=,tag:zUPq5BmNO4cFa6uTQlZEIg==,type:str]
sops:
  age:
    - recipient: age1a4mp4uwu56ds9300vmyk9q77wzqs52338a8wjl0e442xs2v0jscscdf07k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQalM3YVpXS1hVbXd0dFdt
        dS9Xd2dFZEpBQk52Y3FuVW1MeUwvQlB1VUV3CmpmZFAwemJpTDBMQWpGaVEwVDdj
        M0k4eEszbTJxM3FTQUtTZ0VLKzhMOXMKLS0tIFU2NXROMnYvb0MrM2k2YllTQmVw
        T1BBTjljNkhYSldFVXdkVlRwOXNwN3cK3O+ca+PESFjM2M5SZ2W+2S7/X+FL8i69
        wvMXhBWx7Tqmcn4K/FlnhZ+uINv9673ZtTx2dOn7Y05Ic6EsNJrqzw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-19T02:27:50Z"
  mac: ENC[AES256_GCM,data:D0Bqj5uYgg3PkJkNvxWFNO7gYhz9Zv9jSRsvwtkTQbfZynTuim9UcZHstgTurvLcP+KqIaLoOEhKgpITr2fcTyhsS0TCrPAuIS8K4Trl8c9YSaAbVH89bGD2R6pZByUfqHssZXyje4dAzya+nqMMk966vH9uT4ZwQ9ptHHMp+fE=,iv:vPNc/V0JfQHRiN1QYxII90YDj/ODIo9ojQjQaOCvgpc=,tag:2Tw0cLnUGtxxAzNc8t2k7Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
