apiVersion: v1
kind: Secret
metadata:
  name: bws-secret
  labels:
    external-secrets.io/type: webhook
stringData:
  token: ENC[AES256_GCM,data:W8UaTe36xOqmcPURC+0CEyjpRFYTGxjAVNYqTK7HwI+M2+Ao8OZr6GiH9i9a+CsiyikXr3zMBXRz0gdxZOdBl1zBvTzjxqIzHSiP0/NWOaQe0mNM8eXmTDNpPEq/8w==,iv:yZRz1JwZFMefjGUubztbh2Bn5bXgpEHw3JotGDPOf8s=,tag:GxsOVIZoNulmXU4MotXkdw==,type:str]
  ORG_ID: ENC[AES256_GCM,data:2GNCzD4sUwRvsTPpY4vHrnP54tUFGM8K0LuwOoixvK0INY5G,iv:flRJHHl8lYGDOEbTFCPU3OnqPFkpI9MVJxFVWP8BH5A=,tag:VYIlVSftb/1OKGR+Tuu7zg==,type:str]
sops:
  age:
    - recipient: age1a4mp4uwu56ds9300vmyk9q77wzqs52338a8wjl0e442xs2v0jscscdf07k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTktoRUFBOXV3ZVdVdVFt
        UmdpQWYyckpZb252SktYbjRwZTFhaXpXMlVrClFncFdBQi9uaUVrOFRYMUZDbTZk
        TFArKzZsTUg4UEJiRFFVQU1HWjlUWE0KLS0tIEs3ZGxwZmRmeHVQeGRmbkVHK2NI
        Y2tWMTJSTXJKOUNOOXNVUDAvcytBUVkKMri4ChY4arhBY6WXs3vZzOLT5fclHzAj
        2ETnrLr0MGjlpfFRaksyAROwpmv8s6JsmMOpH99H9m9SdPVv8NKVDg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-12T14:17:04Z"
  mac: ENC[AES256_GCM,data:GvdaNeDCwmsUgeS7ipKm81CQaF+2wCfA7p0/9Q8WSHgwRCZraAKYEi3A4rBASQWn7hbSeMXO+KG4ISxpItbhze+SPXLSbzlp5jJMsO3p2tKcJ0fU7iTJDG1gvASAD6HTj0R1fCNlfr1awBeaX7VUa2ICWn9XuxsHk94lYhEshJA=,iv:BZm22NffcMFNIk1phSeEcfcnnJ55+FB/xvwFTS4xciM=,tag:ilxrRaIB+O2HtyFv4Z445g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
