apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:ZqUAEnf5FnmzGYiUE9BWMiIcB74vaDhU20OJeQGHPalbh0k/k5WdBQ==,iv:qgUXPuDXWU55JCJsm4diB2wITItVpYhr3aKo93kwZa8=,tag:C6EIk76dKFYwwhNxD8KctQ==,type:str]
sops:
  age:
    - recipient: age1a4mp4uwu56ds9300vmyk9q77wzqs52338a8wjl0e442xs2v0jscscdf07k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmVUlRMXBVc0xPQlJtU3JV
        MEV1d3Y2dUd5RHFpVFU0Z3hhZTdUcXpFT1c0ClhXd2p2T0FMQ1doL00xS3R0amlE
        VHNSc1E2UUxhZTM3dDNNeUxpdXhkRGsKLS0tIGFDRVNGS1liOVVkN29rSk9rQnVN
        a0M3ZzF2cGI1L2wxcytHZVNsWUZOSTAKB67v/CLAaR4muMuef8cYhz6E3wV19W8U
        7hKzucEjeTMLYRPmy9p1f3to8fID9ixlR70Ng3L8WR4zO3j1ZV7SHg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-18T13:46:52Z"
  mac: ENC[AES256_GCM,data:FLC6rQ/wMcv4s2GP14fKuk8Ta41wVmeBoYRxKGjMa/0Z+6IpNzvDp0XKR4l79EjT41k/9Nsu7V1kOwQqIBxlKs1unc+e37RWDb4GGeMpqBMRfXs0GSltl4fY5bMFHfEtxv12goK//IQEt+3gaQ5E9pquAxDvQmGio30sO7kdhBw=,iv:q/ff7jKt1XBKB3ZQbVFmcEhhOv92mXbWOlnOg/9CsmE=,tag:kaegMgIbaNMz5YfofCkGAw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
