apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:0nWjudDrkUvALL8TmrPtSjCA9wWh4YZ1QJFxzrbPlShBu4xb2zX+OA==,iv:VZPjZcD1sblFL7y6wCcKKxAGVNUWwRvl2P0yDnBUKJc=,tag:4rfvBl6rSx5iMXqV4FYfzw==,type:str]
sops:
  age:
    - recipient: age1a4mp4uwu56ds9300vmyk9q77wzqs52338a8wjl0e442xs2v0jscscdf07k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5UGZvSEoyMHNoWFBpOHFl
        R0VLZ0dEWWZwWHF5amI2dnZudko3SnoxYmhJClc1aVZhMlh3RkpZeFBrT1EyTk1U
        NWNWb1ZOcmxoZVBBK3dKbVh4cVpmbmsKLS0tIGltQzZHeG1LNzFGVkRDazZhQit6
        aTg2VCt4RCt5Zk9GdVJDZDNCem5veTQKJufPaxm5osv6h3s7b8cbBom5Dt0toWgP
        Rw96NxZ5djKo5kaZ4H5SgXfc5hmR19oFy3ohrYqhPgqC27oK3ejg/A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-17T19:37:44Z"
  mac: ENC[AES256_GCM,data:BdHopMzlgopy4TJvJr32MFOiS2FGbTfqCTmsnfdukWZ7/LxDXutbuXXi0gbktWMeBPqBZvV+GRhD1BOwJPTl2YlxLVKw3mXTL5FZKb10tHTMJu/q489VowaqeoFDeQdzPQVALcyUJw/F6DwhdsTC6Zeha9QNmZiN2CHbRdjN5Nk=,iv:6v9hmXJPaabP0aNx16fWRE32RXDuiIPNEnBNkZeHe4Y=,tag:0Ygu8YvoaO5xzvT6yVP/lg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
