apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:XTI/w4oGBa4cqErw,iv:NBlASUJVN30lkzJuSDCEK1u5LbBWnY26I4b5bZ+cwJ0=,tag:2Y3hyxDxu0M3/tgKDMVzeg==,type:str]
sops:
  age:
    - recipient: age1a4mp4uwu56ds9300vmyk9q77wzqs52338a8wjl0e442xs2v0jscscdf07k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmQ3R3Zmx0alNRNlB0SW1O
        cjliT05keHJESVh5c3NYR3YvVnlybm0zWGx3CkQrUlYzTTJYeWdMR1VpUmhxVE45
        NnNQeW82VkVtTnN3K20vWXhmb3QwOHMKLS0tIDB2cm15MElJdkJ3ZzltT1M0Tmpu
        OTRET2RNbms0THJuUERRd21wZXlSQlUK0IwgRVPqAnk9vyK1VO4mWxA196ImtM75
        0UcT/gd+cbcoOzUVUY5+/77cZNA4EEJj6on9k9ehG/dCAUC98KmjPw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-18T13:46:52Z"
  mac: ENC[AES256_GCM,data:YoLPUaXT3Xne8lgeHVUgyZO5Rlkd3R6z1F/FdkxgVSq42hSWpNyeNzBB5IxT8rmzvVy4yBea+cZoKyFnHJ6NarImvF7sqBXBQROrLzowmGaXDh3Kw6pg8y312hpfr+bevHQwzbxpjP+uL8KPUZRWsI/BzSZSwczRFC7IhhVE29Q=,iv:Cvo1CxZkS9G7MRQhrFXoUaOB48Ll4ZZqFKh9yKndC9E=,tag:b/AKLDJsiYUQ3+dD6rQIxg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
