apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ""
sops:
  age:
    - recipient: age1a4mp4uwu56ds9300vmyk9q77wzqs52338a8wjl0e442xs2v0jscscdf07k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJWDdQK2l5QzdiYlVac3FE
        RllJNTRYYit6eFVCRFhrTUN3TlNtK2htTjNVCnRoQlpXYmUxdmxRN3VyQTBISExx
        ZFB6UzdVbjNWWTgvcUFZKy9kOFZYSW8KLS0tIDl0WUtUREJkdWJBeXpxWWROQ282
        VE9ZNmQzbHJDMDhvcDdzeUZybkVDN00K6HNmxXGgK9go8/SCI/yQ1WwV08PKTE8l
        pFvld45xeO7QliQhBQRidbEpNh9aKNrrJu8NI9pSs2s0U1mVWGhANA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-17T19:37:44Z"
  mac: ENC[AES256_GCM,data:y7pYeQ3wGovFMUyXbO9p67wE9Ql4lhUtHB9DXH9tz418QwhP260TLfKLlhczfgjZmneGOtwKOzNwyI2KsXok5AGBfOOzqHALkYDiz+kaAC/fRA/MXMgoYrZ+dH5sVsOpwjzhvem8vQpOMAkpDtgp4EYiIws7TaKUug0MWfuBSPc=,iv:qBxeQX8379Og3YE0DYhMSR52rFTjCnVhU8jCp/hwsS8=,tag:czZT3NJgzKZkysBp8eX4eA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
