apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ""
sops:
  age:
    - recipient: age1a4mp4uwu56ds9300vmyk9q77wzqs52338a8wjl0e442xs2v0jscscdf07k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDT1N2OXZnUStPb0V3YjhO
        UHpMejNyZis5RHEzQTNueUM4c3pPODkwamo0CmI4VHJvZnRZVkErbTNoRE93Q3RK
        K3ljVU9QeW1NelVkeThGMCtXUTFYdmcKLS0tIFJOd2xFU3VINno2QjY3UkdJUEVB
        Y3VsWnJmZk9pemdUZ280ZW9rWnlMcFkKy2agT1hUHvJ0NgikuT+aGa76C9bXfhaI
        BvzL6jgk0r47/eWlQVJ2T1jbL5L1ydvMrtYE39NAMOvFjsgLvoF0Ng==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-18T13:46:52Z"
  mac: ENC[AES256_GCM,data:8qwJghTvv+5dIl7sJC9Ttlwh660lp2XMBlB8Eeu2/aOdllfqMZq8VQl0neArhp+c4pKHy9V0MWGWzp2qHO1d+jEqy8b4rU6nBv2h7zAlJCs68HPgV8rCcrinBIQnYz3IVCBqU9sWnicyeFKm9y+540iQd353P1zDD+PrIEJJVrY=,iv:LYffUBtNFP6UjQzMjsaV2Tvgheb4e5zjG2vwjQzcsg8=,tag:hnEM43MlfuM1W1aLkXPVkw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
