apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:CZjRa6NObMrASW1NxLpqFdNijBBKRQGgc2NVQfTAcPl4y1QgwGy1bkxUvMb6EllYPPPmPURfM90QZ6Ho8nSniorEBFKHO0ZabBd8KYY1kB2quMuPfB/12pIG7p3ei73lm9VSyQwjoPGdr8IFOxhcNqYH10VJfMDEeZAXqj/FDRh9CGzWW1T3T9e/19e4q9+ZEqwdOidJiUJs5vN7WmLHQ5DTRUbK+WnTW0n6gg3oDSvIcMLC,iv:dt2hESiaYKX9Gk0c/p1/G0ObrY59AckcPjtT+o2zaS8=,tag:o1WLDPfDeUCmEP9MBEWHdA==,type:str]
sops:
  age:
    - recipient: age1a4mp4uwu56ds9300vmyk9q77wzqs52338a8wjl0e442xs2v0jscscdf07k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSOWV2YllqV2JxVFhjRGFF
        bGc5c0NGUC9JazZFbHFDaGE3eUpzcngxK1g4CjA3a2J0K0hEWEM2NW1OakkyYmcz
        QnVTakJ2Qm5KeFlrZVhrQmtXNEZXckUKLS0tIDN3WFZYVTUzWHhwb3RvYlF5dUNV
        NW1BdXdjK1VJamFEbXhEazUxYUxHb2cKx0aL8v7OWqP59JX935m1JNguQldOaD+v
        wMBDFY+3sAtZPC7X3p9ZVmEhm6pj9b/f/pjaEyXiKnjyrhXSXuolSg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-17T19:37:44Z"
  mac: ENC[AES256_GCM,data:d8K8WtJIN/akWKMRVMhAmaPTNDSn6ZdA/CSwGp41E/4ZzN+A1rgybtNkddX148LsRTVmVr3zb8Nmxvvaa7ZPHqzGolANTRid7pCaIKJc8G5kuVmw+PskpBVI4LQ51U5kaa6+O84IG2t70coRBQ6YYt+Gg+scqf0UXjVKHTa/rhw=,iv:C7+CMIYkHzMzURVBqmq2W+93auvNNKO0fj/4AsypD9U=,tag:yW3W+UcFLBRoT7qtZO6Ptw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
