apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:tSd57m3UlRt3ManyALPxU8wI8kT8mvQ7/PTdjJ7ffkS8+4hHxOMjnXrl7uP15KoOyOiLBHlVOuD4vTkWdDLpGqgG/a4tDPtl1zJ2ziUi3n10YDWn+eGd4eA83NvlGN4gwVLGKQlPDSF0Kw3OHqyfi+G/R4KnW9bGQX7nZ1gVAhCWKVTO+nLJEukmm2F7DnF6rhQaxiWZNig1NJFmuANufKprXkKznifAb3bQlWI5toB6yz2X,iv:bhp9wrKE6J0vna9ybSrPspzqWJgDZEDYVeUZdjY8Uv0=,tag:LLr3rjHJttTcR2Nbt4ruxw==,type:str]
sops:
  age:
    - recipient: age1a4mp4uwu56ds9300vmyk9q77wzqs52338a8wjl0e442xs2v0jscscdf07k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbmZPSEFUMEpkT0YxaWNP
        aXZtcmZwbk9jMnV1VEIzSjZiNy8vOXpGSmg0CmZQVjJOQlFTM3AvS2gweVA4dFJP
        UWRmUGhIKzlTVWlRSlljcDliK0ZoMncKLS0tIG9vVWxEVUxneFl0aXZrYXVCanVt
        Y3g0djN3SmhkQk92eHcybk4vZmswR1kKNVWco0vQB3nCAkUHD7G9Qsc0actVIqoH
        9N9/Xs4g3q0FrUMflIyqOaH1oQA07OvdPVqYu2h+EtWbvA4iCHmPoQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-18T13:46:52Z"
  mac: ENC[AES256_GCM,data:uyOzVCG6O01N37F2JlrSHD1VpDPLazVsYi3VC1tsU697slY20r2XWZVlMYGGM0wjtdSR9JASKEWhNOW/sdVHm5bwomTZUTQ4iXozUUzzrbbS/0E3+RbZfYYEV1zDjLZNTl0TsHEXysE1P7pujIFCq2udcs3wsXYDiQl5stUNxDM=,iv:lPp8KHX6GoYOtoNxSD5OqID0Z3eLn3rIcBPwHc/j5GA=,tag:pTpOIRkIauSui8p1pGNxqQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
