apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:ESDXWpFOPkA7zFxUoSzef7MRLydmouVu83C5dSoEKOCUfNGc4JzZRQ==,iv:GopWI8eZCkfj9NzhtH3NVWcuZIwe8FsB/BppTnJdgDs=,tag:xWzTg8jW+Q0Og/Cjgdba3Q==,type:str]
sops:
  age:
    - recipient: age1a4mp4uwu56ds9300vmyk9q77wzqs52338a8wjl0e442xs2v0jscscdf07k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiSmJWeHdEWHVocHlpU25u
        Ull5VEZnVGJDQ09ab0tUaDZnaFFvM0ZKa3d3CjVxQy84MlZtSmhkdDFYMzQ0aTZs
        UVR5bG1pM1kvcitHVXIvNXdCbnBGRU0KLS0tIDBjejhGMS9XZEdmcSsvd3RlWjJF
        K2p3eCtvbWZyWUdPaENqVjY0YkVWYTQKYRd4rOmrc/WzHGhbu3IgL6sAQN30xJXO
        2OvUzjtRI9DV49yEjt26Ioigs1laDJIzJxCm7NdnCUnv2nEAi+wG+Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-18T13:46:52Z"
  mac: ENC[AES256_GCM,data:BNoFlmuh1fd3hwhEcA93JWJFgo/u43qSACFqpMA7V/m46eWbaVdcCksKabpix+E/LhOOBVqJ4rcT4pEbYMqzCco27RyGBTWe5yJhFlHh+HNvf2dL2x6PMc0fBUW5U4v6Z2Ocly5ueLOmkas3ymH9GRiurDvypa9L6MO1AvlGZUg=,iv:I+nyKjAeczoNPPeEhsdaOJjXH2qOFqgurNhIy7ZliX4=,tag:FiYbbw9xSJSB1hQXJrKDIg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
