apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:IvDYIjxwCixNisV5Am3GVPIxYMAE+b1U398NsPSBqMeGmJTEB7B5Bg==,iv:tHnDcvdGwRtFApTn+eypg5JEKOxbzG3MdXTUi8rPtHM=,tag:JHYMvNnQjmbkNALb1V6H/A==,type:str]
sops:
  age:
    - recipient: age1a4mp4uwu56ds9300vmyk9q77wzqs52338a8wjl0e442xs2v0jscscdf07k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNlNkZU5BcnFnVWhxS1BM
        eExVVFlrVjVvNDJWbm1LMjF5WllKWk5Pa3pRClpRQ25VOGFSUjdaSlU3aWwyUGRj
        eG8zTFRiUzNNTTdQUlAvWnpPNzM0VXMKLS0tIEpaTzJORHd3SFF0VGhFSkJEQU9l
        RHRNTE5PUUoyeG1FWkx2ZkZBaGwxOEkKDNwCKZIY88NQGHTUitq1VES9HDsVRasB
        RGBlQvBjYOwk4QIL3fZ6fKHL9IMUMbos7ZQn7N7xpXAn/6P1GFxnNg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-17T19:37:44Z"
  mac: ENC[AES256_GCM,data:IfDmQLegwEGqOO1L7SCFOLOabgO2FL9X6ONd/z14R1C+AioYdrHEYgsp/3IAPd9pdnrNkLJzHu7VUPdsLMyjMCzhKVukFVz/wJCZGsbvBykuYyrgnPMDDAjwfj3GtzBOZ9iPZ0jSGMgQBvvFZBmZfXM7U9+P1Dh6knEZfgw23bs=,iv:OF9agNtbRwl3M1kf/iJoOATctoPFPuuLcXSmMhc2SaQ=,tag:lMf4AuS4oZ83c0Q7cwabow==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
